### ISSUE TITLE
Lol it's depecrecated fag groetjes Ivo

### ISSUE THREAD

**Issue by IvovdBruggen** [GrimReaperFloof/ChocolateSkypeBot#1]
https://github.com/GrimReaperFloof/ChocolateSkypeBot/blob/aade46a591b70b39b08ae7ab0d806402dbb0e335/Chocolate%20Skype%20Bot%20Source/Chocolate%20Skype%20Bot/Chocolate%20Skype%20Bot/Form1.vb#L1

**Comment by IvovdBruggen** [comment]
Git rekt

**Comment by GrimReaperFloof** [comment]
lol
